export const ARABIC_LETTERS = [
  { name: 'Alif', display: 'ا', shapes: ['ا', 'ـا', 'أ', 'ـأ', 'إ', 'ـإ', 'آ', 'ـآ'] },
  { name: 'Ba', display: 'ب', shapes: ['ب', 'بـ', 'ـبـ', 'ـب'] },
  { name: 'Ta', display: 'ت', shapes: ['ت', 'تـ', 'ـتـ', 'ـت', 'ة', 'ـة'] },
  { name: 'Tha', display: 'ث', shapes: ['ث', 'ثـ', 'ـثـ', 'ـث'] },
  { name: 'Jeem', display: 'ج', shapes: ['ج', 'جـ', 'ـجـ', 'ـج'] },
  { name: 'Hha', display: 'ح', shapes: ['ح', 'حـ', 'ـحـ', 'ـح'] },
  { name: 'Kha', display: 'خ', shapes: ['خ', 'خـ', 'ـخـ', 'ـخ'] },
  { name: 'Dal', display: 'د', shapes: ['د', 'ـد'] },
  { name: 'Thal', display: 'ذ', shapes: ['ذ', 'ـذ'] },
  { name: 'Ra', display: 'ر', shapes: ['ر', 'ـر'] },
  { name: 'Zay', display: 'ز', shapes: ['ز', 'ـز'] },
  { name: 'Seen', display: 'س', shapes: ['س', 'سـ', 'ـسـ', 'ـس'] },
  { name: 'Sheen', display: 'ش', shapes: ['ش', 'شـ', 'ـشـ', 'ـش'] },
  { name: 'Sad', display: 'ص', shapes: ['ص', 'صـ', 'ـصـ', 'ـص'] },
  { name: 'Dad', display: 'ض', shapes: ['ض', 'ضـ', 'ـضـ', 'ـض'] },
  { name: 'Tah', display: 'ط', shapes: ['ط', 'طـ', 'ـطـ', 'ـط'] },
  { name: 'Zah', display: 'ظ', shapes: ['ظ', 'ظـ', 'ـظـ', 'ـظ'] },
  { name: 'Ain', display: 'ع', shapes: ['ع', 'عـ', 'ـعـ', 'ـع'] },
  { name: 'Ghain', display: 'غ', shapes: ['غ', 'غـ', 'ـغـ', 'ـغ'] },
  { name: 'Fa', display: 'ف', shapes: ['ف', 'فـ', 'ـفـ', 'ـف'] },
  { name: 'Qaf', display: 'ق', shapes: ['ق', 'قـ', 'ـقـ', 'ـق'] },
  { name: 'Kaf', display: 'ك', shapes: ['ك', 'كـ', 'ـكـ', 'ـك'] },
  { name: 'Lam', display: 'ل', shapes: ['ل', 'لـ', 'ـلـ', 'ـل'] },
  { name: 'Meem', display: 'م', shapes: ['م', 'مـ', 'ـمـ', 'ـم'] },
  { name: 'Noon', display: 'ن', shapes: ['ن', 'نـ', 'ـنـ', 'ـن'] },
  { name: 'Ha', display: 'ه', shapes: ['ه', 'هـ', 'ـهـ', 'ـه'] },
  { name: 'Waw', display: 'و', shapes: ['و', 'ـو', 'ؤ', 'ـؤ'] },
  { name: 'Ya', display: 'ي', shapes: ['ي', 'يـ', 'ـيـ', 'ـي', 'ئ', 'ئـ', 'ـئـ', 'ـئ'] },
  { name: 'Hamza', display: 'ء', shapes: ['ء'] },
];

export const HARAKAT = [
  { name: 'Fatha', display: '◌َ', char: 'َ' },
  { name: 'Damma', display: '◌ُ', char: 'ُ' },
  { name: 'Kasra', display: '◌ِ', char: 'ِ' },
  { name: 'Sukun', display: '◌ْ', char: 'ْ' },
  { name: 'Shadda', display: '◌ّ', char: 'ّ' },
  { name: 'Tanwin Fatha', display: '◌ً', char: 'ً' },
  { name: 'Tanwin Damma', display: '◌ٌ', char: 'ٌ' },
  { name: 'Tanwin Kasra', display: '◌ٍ', char: 'ٍ' },
];
